approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

npmScopes:
  rm-hull:
    npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.15.0.cjs
