name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org"

      - run: yarn install --frozen-lockfile

      - run: yarn lint

      # Build and publish directly
      - name: Publish package
        uses: changesets/action@v1
        with:
          publish: npm
          version: false
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
