name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Checkout full history for tagging
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # Node.js setup with Yarn cache
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: "yarn"
          registry-url: "https://registry.npmjs.org"

      # Install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Lint
      - name: Lint
        run: yarn lint

      # Build
      - name: Build
        run: yarn build

      # Publish and commit version bump + changelog directly on main
      - name: Publish package
        uses: changesets/action@v1
        with:
          publish: npm
          version: true # Commit version bumps & changelog
          commitMode: git-cli # Use direct git commit, no PR branch
          createGithubReleases: true # GitHub release
          setupGitUser: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
