name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo with full history for proper tagging
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # Set up Node.js with caching
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: "yarn"
          registry-url: "https://registry.npmjs.org"

      # Install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Lint
      - name: Lint
        run: yarn lint

      # Build package
      - name: Build
        run: yarn build

      # Publish package, commit version bump & changelog, create release
      - name: Publish package
        uses: changesets/action@v1
        with:
          publish: npm
          version: true # Commit version bumps & changelog
          createGithubReleases: true # Create GitHub release
          setupGitUser: true # Set git author for commits
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
